import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* GLOBAL NAVBAR */}
        <nav className="fixed top-0 w-full bg-gray-900/90 backdrop-blur-md border-b border-gray-800 p-4 z-50">
          <div className="max-w-4xl mx-auto flex justify-center gap-8">
            <Link href="/" className="text-gray-300 hover:text-white transition-colors font-medium">Home</Link>
            <Link href="/ai-playground" className="text-gray-300 hover:text-white transition-colors font-medium">AI Playground</Link>
            <Link href="/dashboard" className="text-gray-300 hover:text-white transition-colors font-medium">Dashboard</Link>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
